### PR TITLE
win: build with WIN32_LEAN_AND_MEAN macro defined globally

### PR DESCRIPTION
**Pull request by sergio-nsk**

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Can you try to add a commit that removes `-user` from gcovr command?

**Comment by nmoinvaz** [comment]
It shouldn't be using brew. It should still use python. All I was suggesting was removing `-user`.

**Comment by nmoinvaz** [comment]
`brew` not available on Windows and Linux so..

**Comment by sergio-nsk** [comment]
This is `macos.yaml`.

**Comment by nmoinvaz** [comment]
Hmm

**Review by nmoinvaz — APPROVED** [review]

**Pull request merged**
