### PR TITLE
Alt fix of unused var warning in release mode with threadpool_winxp

### PR DESCRIPTION
**Pull request by sergio-nsk**
Don't need `#ifdef _DEBUG` inside the sources.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
This is an interesting idea. I might go forward a `UNUSED` macro instead because I just learned that there are some other files that have unused warnings with /W4 on MSVC.

**Comment by nmoinvaz** [comment]
I think this is too complex. I had something simple in mind. I will open a new PR.

**Comment by nmoinvaz** [comment]
> Fix warning: comparison of integers of different signs

I think this is already resolved in master.

**Comment by sergio-nsk** [comment]
> I think this is already resolved in master.

This is the diff with master:
image

The warning:
image

**Comment by sergio-nsk** [comment]
> I think this is too complex. I had something simple in mind. I will open a new PR.

Once done, simple use. 

This is too complex and requires knowledge how  `LOG_DEBUG` is implemented.
```c
#ifdef _DEBUG
  int id = ...
#endif
```

**Comment by nmoinvaz** [comment]
Regarding the `-1` cast...

`master` branch uses `uintptr_t` instead of `HANDLE` for `handle` variable.

**Comment by nmoinvaz** [comment]
I see unsigned change. I have added that commit to my PR.

**Pull request closed without merging**
